# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
       working-directory: A2
    - run: npm run build --if-present
      working-directory: A2
    - run: npm test
      working-directory: A2
    - name: Deploy
      working-directory: A2
      run: |
        git config --global user.name "SamarRamsha407"
        git config --global user.email "u2017407@giki.edu.pk"
        git remote set-url origin https://f5bf90771fba38e53d303bc34fb27a46de431e88@github.com/A2
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }} 
